# Generated by Django 5.1.3 on 2024-11-27 12:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Automobilio_modelis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Marke', models.CharField(max_length=30, verbose_name='Markes pavadinimas')),
                ('Modelis', models.CharField(max_length=30, verbose_name='Modelio pavadinimas')),
            ],
        ),
        migrations.CreateModel(
            name='Paslauga',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Pavadinimas', models.TextField(help_text='Trumpas paslaugos aprašymas', max_length=1000, verbose_name='Aprašymas')),
                ('Kaina', models.IntegerField(help_text='Ivedama kaina', verbose_name='Kaina')),
            ],
        ),
        migrations.CreateModel(
            name='Automobilis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Valstybinis_NR', models.CharField(max_length=9, verbose_name='Numeris')),
                ('VIN_kodas', models.CharField(max_length=25, verbose_name='VIN numeris')),
                ('Klientas', models.CharField(max_length=25, verbose_name='Klientas')),
                ('Automobilio_modelis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='servis.automobilio_modelis')),
            ],
        ),
        migrations.CreateModel(
            name='Uzsakymas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Data', models.DateField(verbose_name='Data')),
                ('Automobilis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='servis.automobilis')),
            ],
        ),
        migrations.CreateModel(
            name='Uzsakymo_ilute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Kiekis', models.CharField(max_length=10, verbose_name='Paslaugu kiekis')),
                ('Paslauga', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='servis.paslauga')),
                ('Uzsakymas', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='servis.uzsakymas')),
            ],
        ),
    ]
