# Generated by Django 5.1.3 on 2024-11-27 13:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('servis', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Uzsakymo_ilute',
            new_name='Uzsakymo_eilute',
        ),
    ]
