# Generated by Django 5.1.3 on 2024-11-27 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servis', '0002_rename_uzsakymo_ilute_uzsakymo_eilute'),
    ]

    operations = [
        migrations.AlterField(
            model_name='automobilio_modelis',
            name='marke',
            field=models.CharField(max_length=30, verbose_name='Markės pavadinimas'),
        ),
        migrations.AlterField(
            model_name='automobilis',
            name='Klientas',
            field=models.CharField(max_length=50, verbose_name='Kliento Vardas Pavardė'),
        ),
        migrations.AlterField(
            model_name='automobilis',
            name='VIN_kodas',
            field=models.CharField(max_length=25, verbose_name='Mašinos VIN numeris/kodas'),
        ),
        migrations.AlterField(
            model_name='automobilis',
            name='Valstybinis_NR',
            field=models.CharField(max_length=10, verbose_name='Mašinos valstybinis numeris'),
        ),
    ]
