# Generated by Django 5.1.3 on 2024-11-29 08:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('servis', '0005_rename_automobilio_modelis_automobiliomodelis_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Uzsakymo_eilute',
            new_name='UzsakymoEilute',
        ),
    ]
