# Generated by Django 5.1.3 on 2024-11-29 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servis', '0006_rename_uzsakymo_eilute_uzsakymoeilute'),
    ]

    operations = [
        migrations.AddField(
            model_name='uzsakymas',
            name='status',
            field=models.CharField(blank=True, choices=[('v', 'Vykdoma'), ('l', 'Laukiama'), ('p', 'Paruošta'), ('n', 'Nukelta')], default='l', help_text='Statusas', max_length=1),
        ),
    ]
